language: php

services:
    - docker
    - redis

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""
    global:
        - secure: jVVuI4fQj8i1R6LG0Eym2UoDNmUOc/MtCDk0JtvzZpUFWf3QcMvCR/0qclptBT0bH1j33AsLSrHIRXDp5Saz/Bk8LZvzKu5nrA3DCL+Wp/Ac3VfOzmWvMiETmt8/03UAr/6DHtYzE98OqSGkHsZcHQQzbi38YQVFHEYWr8/IeHs6eTajT3W2Vtwftnl4BSSZQUiEgQpPBrkKHNw49399otDR7mASwFLykkh+oZVQtTfQkZP1rk+ohDDejJWbBfAvFSyjr00O3MizCHrcS8hE1046goSAZvdI/0glmyM4+QoZPaFpYjIoXuuHRCXkNzM6hHpvvljBDjKgvprWFIlV+JQ7X8+McP/9rAxMMANMwrQOdnxwtTcSsJWpHpv0ViPql1PigqBYHm/kv6ddRXHMjVrBhzfgFArXkhumWFq8pqEo93niExFigkSFtGFPbxQ9vkj/4vclV6fgcYMnXigg0yI7rio2F+xK74R98rS5BsqFGZ4bd4Sanat3J1+Dkq03ZnG+4lDT4i6Gdrkto4s2vNHj34jlIaKE17w+h2F4EGBvjZwk/+3ck7uotrsefQnxDPAAhWqL0Azt+V/I1Aha10xDWBlbdgRiNj5+Ionc99fPjCAWktXCGXIpDIvzmIS7LYMf58cdSnjumm5oLrFHp2Z/XO3Wjh7dddVtQ1qvWsw=
        - secure: 3Z3IfKQiMMOZOMPkS2cYyrO5AoT4gmASNZmS1yJ+5eA4OoI/EAXScHC9gpKdNAb4JWNRoZsns6D8DcCl3ucTyhBpIjDu2C/v9nWOVKIwaSqE34aUilUVhTGw5KPZ1RrvN6LxM1K9UtGy/eU8/7iPqIQv0+CBiv1zoNVALUc/0xW+UX5zc8xxU0cG5wCvkL/M/R0MZvT/dtQCLPRskjCdhQh64oyou50+h1qnBrxkYawpWUTEZ1jZFQZJtIjaPmKCiAUyxxJco56pIlmR8+Er2M7jyNLXY1Dj4hwCIeZKLigzdgLtkuUiFOFHdu4CYK2VfRWb6lp8rh5ELvbDG3J9cGp6HKnvKxJygmpP29QM/JdZZKUgYN3BWv3uk9/BaxbrFZw02hnWvJSE3FJppz+4wOslEREpuA04q4/lpf9qC3dfWOnni40hPRixeArhag9iWY6lse4Il6S+wuBADKBbyK121aTGBeW/RjNvL9VnSyVbcbNylF91a1tyZrQm6IMIOsEcp3AdHVX00nlTmjCRwashFePQ+qNNFnUOOrx+nEiV67qCYCa6fa1QrzcJHtBWk6g60pe4eWK6zOva4NA0fv+GegaLLCPMym0nQiw8WW8OCqhW3w5FJFdy+kOPDjuMPiw6xVCmMfjNOpPLgMCY2izK7U6bkeeQb5JEfNZVsdo=

jobs:
    allow_failures:
        - php: nightly

php:
    - nightly
    - 8.0
    - 7.4
    - 7.3
    - 7.2

before_script:
    # Increase memory limit & disable xdebug
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini

    # Authenticate Docker Hub
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

    # Update Composer to latest version & install dependencies
    - composer self-update
    - composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - composer test
#    - bash scripts/boot.sh ${COMPOSER_FLAGS}

after_script:
    - composer upload-coverage
    - docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.Size}}'
